---
output: 
  html_document:
    css: !expr here::here("www", "style.css")
#runtime: shiny

pagetitle: "Audit Reports"
---

```{r include=FALSE, message = FALSE, warning=FALSE, error = FALSE, echo = FALSE}
knitr::opts_chunk$set(
  comment = "#>", echo = FALSE, fig.width = 6
)
```


```{r load libraries, message = FALSE, warning=FALSE, error = FALSE, echo = FALSE}
library(shiny)
library(downloadthis)
library(viridis)
library(tidyverse)
library(gt)
library(readr)
library(knitr)
library(here)
library(DT)
library(scales)
```


```{r}
#Define Functions
mkd_table <- function(err_data, title, subtitle) {
  {{err_data}}
  gt(err_data) %>%
  tab_header(
    title = md(title),
    subtitle = paste("Error Message: ", subtitle)
    ) %>%
  tab_options(
    heading.align = "left",
    table.border.top.color = "white",
    column_labels.border.bottom.color = "black",
    table.align = "left",
    table.width = pct(100)
  )
  }
```

```{r, message = FALSE, warning=FALSE, error = FALSE, echo = FALSE}
source(here::here('rscript', 'student_checks.R'))
source(here::here('rscript', 'course_checks.R'))

```

## Student - Audit Reports {.tabset}


### Demographics

```{r, message = FALSE, warning=FALSE, error = FALSE, echo = FALSE}
if(nrow(demo_check_01) > 0) {
  mkd_table(demo_check_01, "Gender", unique(demo_check_01$error_message)) %>%
    cols_label(term = md("**Term**"),
             pidm = md("**PIDM**"),
             banner_id = md("**Student ID**"),
             first_name = md("**First Name**"),
             last_name = md("**Last Name**"),
             gender = md("**Gender**"),
             error_message = md("**Error Message**"),
             banner_table = md("**Table Name(s)**"),
             banner_column = md("**Column Name(s)**")
             ) %>%
    cols_hide(error_message)
}
```

```{r, message = FALSE, warning=FALSE, error = FALSE, echo = FALSE}
if(nrow(demo_check_02) > 0) {
mkd_table(demo_check_02, "County - US", unique(demo_check_02$error_message)) %>%
    cols_label(term = md("**Term**"),
               pidm = md("**PIDM**"),
               banner_id = md("**Student ID**"),
               first_name = md("**First Name**"),
               last_name = md("**Last Name**"),
               admit_country = md("**Country**"),
               admit_county = md("**County**"),
               error_message = md("**Error Message**"),
               banner_table = md("**Table Name(s)**"),
               banner_column = md("**Column Name(s)**")
               ) %>%
    cols_hide(error_message)
}
```

```{r, message = FALSE, warning=FALSE, error = FALSE, echo = FALSE}
if(nrow(demo_check_03) > 0) {
mkd_table(demo_check_03, "State", unique(demo_check_03$error_message)) %>%
    cols_label(term = md("**Term**"),
               pidm = md("**PIDM**"),
               banner_id = md("**Student ID**"),
               first_name = md("**First Name**"),
               last_name = md("**Last Name**"),
               admit_state = md("**State**"),
               error_message = md("**Error Message**"),
               banner_table = md("**Table Name(s)**"),
               banner_column = md("**Column Name(s)**")
               ) %>%
    cols_hide(error_message)
}
```

```{r, message = FALSE, warning=FALSE, error = FALSE, echo = FALSE}
if(nrow(demo_check_04) > 0) {
  mkd_table(demo_check_04, "County - Utah", unique(demo_check_04$error_message)) %>%
    cols_label(term = md("**Term**"),
               pidm = md("**PIDM**"),
               banner_id = md("**Student ID**"),
               first_name = md("**First Name**"),
               last_name = md("**Last Name**"),
               admit_state = md("**State**"),
               admit_county = md("**County**"),
               error_message = md("**Error Message**"),
               banner_table = md("**Table Name(s)**"),
               banner_column = md("**Column Name(s)**")
               ) %>%
    cols_hide(error_message)
    }
```

```{r, message = FALSE, warning=FALSE, error = FALSE, echo = FALSE}
if(nrow(demo_check_05) > 0) {
  mkd_table(demo_check_05, "Missing Country", unique(demo_check_05$error_message)) %>%
    cols_label(term = md("**Term**"),
               pidm = md("**PIDM**"),
               banner_id = md("**Student ID**"),
               first_name = md("**First Name**"),
               last_name = md("**Last Name**"),
               admit_state = md("**State**"),
               error_message = md("**Error Message**"),
               banner_table = md("**Table Name(s)**"),
               banner_column = md("**Column Name(s)**")
               ) %>%
    cols_hide(error_message)
    }
```

```{r, message = FALSE, warning=FALSE, error = FALSE, echo = FALSE, fig.align='left'}
if(nrow(demo_check_07) > 0) {
  mkd_table(demo_check_07, "High School Code", unique(demo_check_07$error_message)) %>%
    cols_label(term = md("**Term**"),
               pidm = md("**PIDM**"),
               banner_id = md("**Student ID**"),
               first_name = md("**First Name**"),
               last_name = md("**Last Name**"),
               age = md("**Age Code**"),
               high_school_code = md("**HS Code**"),
               error_message = md("**Error Message**"),
               banner_table = md("**Table Name(s)**"),
               banner_column = md("**Column Name(s)**")
               ) %>%
    cols_hide(error_message)
}
```
### International Students
```{r, message = FALSE, warning=FALSE, error = FALSE, echo = FALSE}
if(nrow(int_error_01) > 0) {
mkd_table(int_error_01, "Visa Type & Citizenship Code", unique(int_error_01$error_message)) %>%
      cols_label(term = md("**Term**"),
                 pidm = md("**PIDM**"),
                 banner_id = md("**Student ID**"),
                 first_name = md("**First Name**"),
                 last_name = md("**Last Name**"),
                 citz_code = md("**Citizen Code**"),
                 visa_type = md("**Visa Type**"),
                 error_message = md("**Error Message**"),
                 banner_table = md("**Table Name(s)**"),
                 banner_column = md("**Column Name(s)**")
                 ) %>%
      cols_hide(error_message)
      }
```



### Degrees & Programs
```{r, message = FALSE, warning=FALSE, error = FALSE, echo = FALSE, fig.align='left'}
if(nrow(programs_check_01) > 0) {
  mkd_table(programs_check_01, "High School Code", unique(programs_check_01$error_message)) %>%
    cols_label(term = md("**Term**"),
               pidm = md("**PIDM**"),
               banner_id = md("**Student ID**"),
               first_name = md("**First Name**"),
               last_name = md("**Last Name**"),
               cur_prgm = md("**Program 1**"),
               cur_prgm_2 = md("**Program 2**"),
               error_message = md("**Error Message**"),
               banner_table = md("**Table Name(s)**"),
               banner_column = md("**Column Name(s)**")
               ) %>%
    cols_hide(error_message)
    }
```

```{r, message = FALSE, warning=FALSE, error = FALSE, echo = FALSE, fig.align='left'}
if(nrow(programs_check_02) > 0) {
  mkd_table(programs_check_02, "High School Code", unique(programs_check_02$error_message)) %>%
    cols_label(term = md("**Term**"),
               pidm = md("**PIDM**"),
               banner_id = md("**Student ID**"),
               first_name = md("**First Name**"),
               last_name = md("**Last Name**"),
               entry_action = md("**Entry Action**"),
               cur_prgm = md("**Program**"),
               high_school_grad_date = md("**HS Graduation Date**"),
               error_message = md("**Error Message**"),
               banner_table = md("**Table Name(s)**"),
               banner_column = md("**Column Name(s)**")
               ) %>%
    cols_hide(error_message)
}
```

```{r, message = FALSE, warning=FALSE, error = FALSE, echo = FALSE, fig.align='left'}
if(nrow(programs_check_03) > 0) {
  mkd_table(programs_check_03, "High School Code", unique(programs_check_03$error_message)) %>%
    cols_label(term = md("**Term**"),
               pidm = md("**PIDM**"),
               banner_id = md("**Student ID**"),
               first_name = md("**First Name**"),
               last_name = md("**Last Name**"),
               degree = md("**Degree**"),
               major_code = md("**Major Code**"),
               cur_prgm = md("**Program**"),
               error_message = md("**Error Message**"),
               banner_table = md("**Table Name(s)**"),
               banner_column = md("**Column Name(s)**")
               ) %>%
    cols_hide(error_message)
}
```

### Student Type
```{r, message = FALSE, warning=FALSE, error = FALSE, echo = FALSE}
if(nrow(stype_check_01) > 0) {
  mkd_table(stype_check_01, "Returning Students", unique(stype_check_01$error_message)) %>%
    cols_label(term = md("**Term**"),
               pidm = md("**PIDM**"),
               banner_id = md("**Student ID**"),
               first_name = md("**First Name**"),
               last_name = md("**Last Name**"),
               entry_action = md("**Entry Action**"),
               first_term_enrolled = md("**First Term Enrolled**"),
               high_school_grad_date = md("**HS Graduation Date**"),
               error_message = md("**Error Message**")
               ) %>%
    cols_hide(error_message)
}
```

```{r, message = FALSE, warning=FALSE, error = FALSE, echo = FALSE}
if(nrow(stype_check_02) > 0) {
  mkd_table(stype_check_02, "High School Concurrent Student", unique(stype_check_02$error_message)) %>%
    cols_label(term = md("**Term**"),
               pidm = md("**PIDM**"),
               banner_id = md("**Student ID**"),
               first_name = md("**First Name**"),
               last_name = md("**Last Name**"),
               term_start_date = md("**Term Start Date**"),
               high_school_grad_date = md("**HS Graduation Date**"),
               student_type = md("**Student Type**"),
               error_message = md("**Error Message**")
               ) %>%
    cols_hide(error_message)
}
```

```{r, message = FALSE, warning=FALSE, error = FALSE, echo = FALSE}
if(nrow(stype_check_03) > 0) {
  mkd_table(stype_check_03, "High School Concurrent Student & Program", unique(stype_check_03$error_message)) %>%
    cols_label(term = md("**Term**"),
               pidm = md("**PIDM**"),
               banner_id = md("**Student ID**"),
               first_name = md("**First Name**"),
               last_name = md("**Last Name**"),
               cur_prgm = md("**Program**"),
               student_type = md("**Student Type**"),
               entry_action = md("**Entry Action**"),
               error_message = md("**Error Message**")
               ) %>%
    cols_hide(error_message)
}
```

```{r, message = FALSE, warning=FALSE, error = FALSE, echo = FALSE}
if(nrow(stype_check_04) > 0) {
  mkd_table(stype_check_04, "Personal Interest Student", unique(stype_check_04$error_message)) %>%
    cols_label(term = md("**Term**"),
               pidm = md("**PIDM**"),
               banner_id = md("**Student ID**"),
               first_name = md("**First Name**"),
               last_name = md("**Last Name**"),
               cur_prgm = md("**Program**"),
               student_type = md("**Student Type**"),
               entry_action = md("**Entry Action**"),
               error_message = md("**Error Message**")
               ) %>%
    cols_hide(error_message)
}
```

```{r, message = FALSE, warning=FALSE, error = FALSE, echo = FALSE}
if(nrow(stype_check_05) > 0) {
  mkd_table(stype_check_05, "Student Level", unique(stype_check_05$error_message)) %>%
    cols_label(term = md("**Term**"),
               pidm = md("**PIDM**"),
               banner_id = md("**Student ID**"),
               first_name = md("**First Name**"),
               last_name = md("**Last Name**"),
               student_level = md("**Student Level**"),
               student_type = md("**Student Type**"),
               entry_action = md("**Entry Action**"),
               error_message = md("**Error Message**")
               ) %>%
    cols_hide(error_message)
}
```

```{r, message = FALSE, warning=FALSE, error = FALSE, echo = FALSE}
if(nrow(stype_check_06) > 0) {
  mkd_table(stype_check_06, "Student Enrollment", unique(stype_check_06$error_message)) %>%
    cols_label(term = md("**Term**"),
               pidm = md("**PIDM**"),
               banner_id = md("**Student ID**"),
               first_name = md("**First Name**"),
               last_name = md("**Last Name**"),
               student_level = md("**Student Level**"),
               first_term_enrolled = md("**First Term Enrolled**"),
               student_type = md("**Student Type**"),
               entry_action = md("**Entry Action**"),
               error_message = md("**Error Message**")
               ) %>%
    cols_hide(error_message)
}
```

```{r, message = FALSE, warning=FALSE, error = FALSE, echo = FALSE}
if(nrow(stype_check_07) > 0) {
  mkd_table(stype_check_07, "Transfer Student", unique(stype_check_07$error_message)) %>%
    cols_label(term = md("**Term**"),
               pidm = md("**PIDM**"),
               banner_id = md("**Student ID**"),
               first_name = md("**First Name**"),
               last_name = md("**Last Name**"),
               student_level = md("**Student Level**"),
               last_transfer_term = md("**Last Transfered Term**"),
               student_type = md("**Student Type**"),
               entry_action = md("**Entry Action**"),
               error_message = md("**Error Message**")
               ) %>%
    cols_hide(error_message)
}
```

```{r, message = FALSE, warning=FALSE, error = FALSE, echo = FALSE}
if(nrow(stype_check_08) > 0) {
  mkd_table(stype_check_08, "Student Level", unique(stype_check_08$error_message)) %>%
    cols_label(term = md("**Term**"),
               pidm = md("**PIDM**"),
               banner_id = md("**Student ID**"),
               first_name = md("**First Name**"),
               last_name = md("**Last Name**"),
               student_level = md("**Student Level**"),
               student_type = md("**Student Type**"),
               entry_action = md("**Entry Action**"),
               error_message = md("**Error Message**")
               ) %>%
    cols_hide(error_message)
}
```

```{r, message = FALSE, warning=FALSE, error = FALSE, echo = FALSE}
if(nrow(stype_check_09) > 0) {
  mkd_table(stype_check_09, "Student Cohort", unique(stype_check_09$error_message)) %>%
    cols_label(term = md("**Term**"),
               pidm = md("**PIDM**"),
               banner_id = md("**Student ID**"),
               first_name = md("**First Name**"),
               last_name = md("**Last Name**"),
               sgrchrt_chrt_code = md("**Cohort**"),
               sgrchrt_term_code_eff = md("**Cohort Term**"),
               first_term_enrolled = md("**First Term Enrolled**"),
               last_term_enrolled = md("**Last Term Enrolled**"),
               student_type = md("**Student Type**"),
               entry_action = md("**Entry Action**"),
               error_message = md("**Error Message**")
               ) %>%
    cols_hide(error_message)
}
```

```{r, message = FALSE, warning=FALSE, error = FALSE, echo = FALSE}
# if(nrow(stype_check_10) > 0) {
#   mkd_table(stype_check_10, "First-time Freshman", unique(stype_check_10$error_message)) %>%
#     cols_label(term = md("**Term**"),
#                pidm = md("**PIDM**"),
#                banner_id = md("**Student ID**"),
#                first_name = md("**First Name**"),
#                last_name = md("**Last Name**"),
#                first_term_enrolled = md("**First Term Enrolled**"),
#                high_school_grad_date = md("**HS Graduation Date**"),
#                days_since_hs_graduation = md("**Days Since HS Graduation**"),
#                student_type = md("**Student Type**"),
#                entry_action = md("**Entry Action**"),
#                error_message = md("**Error Message**")
#                ) %>%
#     cols_hide(c('error_message', 'term_start_date')) %>%
#   br()
# }
```

```{r, message = FALSE, warning=FALSE, error = FALSE, echo = FALSE}
if(nrow(stype_check_11) > 0) {
  mkd_table(stype_check_11, "Student Enrollment", unique(stype_check_11$error_message)) %>%
    cols_label(term = md("**Term**"),
               pidm = md("**PIDM**"),
               banner_id = md("**Student ID**"),
               first_name = md("**First Name**"),
               last_name = md("**Last Name**"),
               student_level = md("**Student Level**"),
               first_term_enrolled = md("**First Term Enrolled**"),
               student_type = md("**Student Type**"),
               entry_action = md("**Entry Action**"),
               error_message = md("**Error Message**")
               ) %>%
    cols_hide(error_message)
}
```

```{r, message = FALSE, warning=FALSE, error = FALSE, echo = FALSE}
if(nrow(stype_check_12) > 0) {
  mkd_table(stype_check_12, "Transfer Student", unique(stype_check_12$error_message)) %>%
    cols_label(term = md("**Term**"),
               pidm = md("**PIDM**"),
               banner_id = md("**Student ID**"),
               first_name = md("**First Name**"),
               last_name = md("**Last Name**"),
               student_level = md("**Student Level**"),
               last_transfer_term = md("**Last Transfer Term**"),
               student_type = md("**Student Type**"),
               entry_action = md("**Entry Action**"),
               error_message = md("**Error Message**")
               ) %>%
    cols_hide(error_message)
}
```

```{r, message = FALSE, warning=FALSE, error = FALSE, echo = FALSE}
if(nrow(stype_check_13) > 0) {
  mkd_table(stype_check_13, "Student Level", unique(stype_check_13$error_message)) %>%
    cols_label(term = md("**Term**"),
               pidm = md("**PIDM**"),
               banner_id = md("**Student ID**"),
               first_name = md("**First Name**"),
               last_name = md("**Last Name**"),
               student_level = md("**Student Level**"),
               student_type = md("**Student Type**"),
               entry_action = md("**Entry Action**"),
               error_message = md("**Error Message**")
               ) %>%
    cols_hide(error_message)
}
```


### Courses

```{r, message = FALSE, warning=FALSE, error = FALSE, echo = FALSE}
if(nrow(crse_check_01) > 0) {
  mkd_table(crse_check_01, "Student Level", unique(crse_check_01$error_message)) %>%
    cols_label(term = md("**Term**"),
               crn = md("**CRN**"),
               subject_code = md("**Subject**"),
               section_number = md("**Section**"),
               enrollment = md("**Enrollment**"),
               error_message = md("**Error Message**")
               ) %>%
    cols_hide(error_message)
}
```

```{r, message = FALSE, warning=FALSE, error = FALSE, echo = FALSE}
if(nrow(crse_check_01) > 0) {
  mkd_table(crse_check_01, "Student Level", unique(crse_check_01$error_message)) %>%
    cols_label(term = md("**Term**"),
               crn = md("**CRN**"),
               subject_code = md("**Subject**"),
               section_number = md("**Section**"),
               enrollment = md("**Enrollment**"),
               error_message = md("**Error Message**")
               ) %>%
    cols_hide(error_message)
}
```

```{r, message = FALSE, warning=FALSE, error = FALSE, echo = FALSE}
if(nrow(crse_check_02) > 0) {
  mkd_table(crse_check_02, "Student Level", unique(crse_check_02$error_message)) %>%
    cols_label(term = md("**Term**"),
               crn = md("**CRN**"),
               subject_code = md("**Subject**"),
               section_number = md("**Section**"),
               start_time_1 = md("**Start Time**"),
               enrollment = md("**Enrollment**"),
               error_message = md("**Error Message**")
               ) %>%
    cols_hide(error_message) %>%
    cols_move(columns = start_time_1, after = section_number)
}
```
